#!/bin/sh

. "$(dirname "$0")/.common.sh"
. "$lbu/scripts/common.func"

set -e

test ! -s "$DESTDIR/var/lib/dpkg/status" || exit 0

apt-get update && apt-get -y install $inst_pkgs

debootstrap --variant=minbase $dist $DESTDIR $repo

cat >"$DESTDIR/etc/apt/sources.list" <<EOF
deb $repo $dist main contrib non-free
${no_sec:+#}deb http://security.debian.org/debian-security ${dist}-security main contrib non-free non-free-firmware
EOF

mkdir -p "$DESTDIR/etc/apt/sources.list.d"
cat >>"$DESTDIR/etc/apt/sources.list.d/backports.list" <<EOF
${no_bpo:+#}deb http://cdn.debian.net/debian ${dist}-backports main contrib non-free
EOF
