#!/bin/sh

. "$(dirname "$0")/.common.sh"
. "$lbu/scripts/common.func"

: ${cdeb_suites:=/usr/share/cdebootstrap/suites}
: ${cdeb_config:=generic}
: ${cdeb_keyring:=debian-archive-keyring.gpg}

set -e

test ! -s "$DESTDIR/var/lib/dpkg/status" || exit 0

grep -q "^Suite: $dist$" "$cdeb_suites" || {
  echo "Adding $dist to $cdeb_suites"
  cat >>"$cdeb_suites" <<EOF
Suite: $dist
Config: $cdeb_config
Keyring: $cdeb_keyring

EOF
}

test -z "$http_proxy$ftp_proxy" || {
  mkdir -p "$DESTDIR${apt_prx_conf%/*}"
  _dq='"'
  cat >"$DESTDIR$apt_prx_conf" <<EOF
${http_proxy:+Acquire::http::Proxy ${_dq}${http_proxy}${_dq};}
${ftp_proxy:+Acquire::ftp::Proxy ${_dq}${ftp_proxy}${_dq};}
EOF
}
cdebootstrap -f minimal $dist $DESTDIR $repo

cat >"$DESTDIR/etc/apt/sources.list" <<EOF
deb $repo $dist main contrib non-free
deb http://security.debian.org/ $dist/updates main contrib non-free
EOF

test ! -d "$extra_deb_dir" || {
  mkdir -p "$DESTDIR/$extra_deb_dir" "$DESTDIR/etc/apt/sources.list.d"
  echo "deb file://${extra_deb_dir} ./" >"$DESTDIR/etc/apt/sources.list.d/$(echo "$extra_deb_dir" | tr / _).list"
  test "$extra_deb_dir/Packages" -nt "$extra_deb_dir" || (cd "$extra_deb_dir"; dpkg-scanpackages . >Packages)
}
