#!/bin/sh

. "$(dirname "$0")/.common.sh"
. "$lbu/scripts/common.func"

set -e

: "${CHFN:=/usr/bin/chfn}"

test ! -e "${DESTDIR}${CHFN}" || enter_chroot "$DESTDIR" "${CHFN}" -f root root || replace_chfn=true

test -z "$replace_chfn" || {
  mv "${DESTDIR}${CHFN}" "${DESTDIR}${CHFN}.dist"
  cp "${DESTDIR}/bin/true" "${DESTDIR}${CHFN}"
}


cat >"$DESTDIR/$inst_sh" <<EOF
#!/bin/sh

export DEBIAN_FRONTEND=noninteractive
apt-get -o APT::Get::List-Cleanup=false update
apt-get -o APT::Get::List-Cleanup=false -y install $pkgs $pkgs_add
EOF
test -z "$pkgs_backports" || echo "apt -o APT::Get::List-Cleanup=false -y install -t ${dist}-backports $pkgs_backports" >>"$DESTDIR/$inst_sh"
test -z "$pkgs_unauthenticated" || echo "apt-get -o APT::Get::List-Cleanup=false -y install --allow-unauthenticated $pkgs_unauthenticated" >>"$DESTDIR/$inst_sh"
echo "apt-get -y upgrade" >>"$DESTDIR/$inst_sh"
test -z "$pkgs_later" || echo "apt-get -o APT::Get::List-Cleanup=false -y install $pkgs_later" >>"$DESTDIR/$inst_sh"

test ! -d "$extra_deb_dir" || mount --bind "$extra_deb_dir" "$DESTDIR/$extra_deb_dir"
enter_chroot "$DESTDIR" sh -e "$inst_sh"

test -z "$replace_chfn" -o ! -e "${DESTDIR}${CHFN}.dist" || {
  mv "${DESTDIR}${CHFN}.dist" "${DESTDIR}${CHFN}"
}
