#!/bin/sh

. "$(dirname "$0")/.common.sh"
. "$lbu/scripts/common.func"

set -e

enter_chroot "$DESTDIR" env DEBIAN_FRONTEND=noninteractive apt-get -o APT::Get::List-Cleanup=false update
enter_chroot "$DESTDIR" env DEBIAN_FRONTEND=noninteractive apt-get -o APT::Get::List-Cleanup=false -y install $pkgs
test -z "$pkgs_backports" ||
  enter_chroot "$DESTDIR" env DEBIAN_FRONTEND=noninteractive apt-get -o APT::Get::List-Cleanup=false -y install -t ${dist}-backports $pkgs_backports
